config/routes.rb
Rails.application.routes.draw do
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :bigint           not null, primary key
#  email           :string           not null
#  name            :string           not null
#  password_digest :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#
# Indexes
#
#  index_users_on_email  (email) UNIQUE
#
class User < ApplicationRecord
  has_secure_password
  validates :email, uniqueness: true, presence: true
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to users_path
    else
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update
      redirect_to users_path
    else
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy!
    # 非同期失敗する
    redirect_to users_path
  end

  private
  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | AnythingApp
    meta[name="viewport" content="width=device-width,initial-scale=1"]
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all'
    = javascript_pack_tag 'application'
  body
    = yield

app/views/users/destroy.js.slim
| $('#user-#{user.id} %>').html('');

app/views/users/edit.html.slim
h2 ユーザー編集
= form_with scope: :user, url: users_path do |f|
  = f.label :name
  = f.text_field :name
  = f.label :email
  = f.email_field :email
  = f.label :password
  = f.password_field :password
  = f.label :password_confirmation
  = f.password_field :password_confirmation
  = f.submit

app/views/users/index.html.slim
h2 ユーザー一覧
= link_to '新規作成', new_user_path
table
  tr
    th scope="col"
      | Name
    th scope="col"
      | Email
  - @users.each do |user|
    tr
      td= user.name
      td= user.email
      td= link_to '編集', edit_user_path(user)
      td id="user-#{user.id}"
        = link_to '削除', user_path(user), method: :delete, data: {confirm: "本当に削除しますか？"},remote: true

app/views/users/new.html.slim
h2 ユーザー作成
= form_with model: @user, local: true do |f|
  = f.label :name
  = f.text_field :name
  = f.label :email
  = f.email_field :email
  = f.label :password
  = f.password_field :password
  = f.label :password_confirmation
  = f.password_field :password_confirmation
  = f.submit